# Generated by Django 5.2.8 on 2025-11-21 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='auction_images/')),
                ('start_price', models.PositiveIntegerField()),
                ('current_price', models.PositiveIntegerField(default=0)),
                ('instant_price', models.PositiveIntegerField(blank=True, null=True)),
                ('bid_unit', models.PositiveIntegerField(default=1000)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('WAITING', '대기중'), ('ACTIVE', '진행중'), ('ENDED', '종료됨'), ('CANCELLED', '취소됨')], default='WAITING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_auctions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
