# Generated by Django 5.2.9 on 2025-12-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_condition_auction_shipping_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_national',
            field=models.BooleanField(default=False, verbose_name='전국 실시간 경매'),
        ),
    ]
